version: "3"
services:
  quizbiz:
    container_name: quizbiz
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - database

  database:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
